### ISSUE TITLE
Directory cleanup

### ISSUE THREAD

**Issue by Vectormike** [zero-to-mastery/mappypals#59]
All components could have just been loaded in App.js rather than Main.js with react-router.

**Comment by sciortinomrc** [comment]
@ArnasDickus  thoughts?

**Comment by ArnasDickus** [comment]
Hello @Vectormike40 I never seen you here before and thanks for raising the issue . If you a member of Zero To Master discord group. I suggest visiting mappypals channel and introduce yourself. 

Getting back to issue. Your issue is neither a feature or a bug, I don't see much point in working on this issue. Currently on Trello board we have a lot more important tasks.

**Comment by saadazghour** [comment]
Hi @ArnasDickus, i don't see any link on README file or any other place, Can you please give me invite link to discord channel here :pray: ??

**Comment by ArnasDickus** [comment]
Hello @Azghour-Saad sorry I can't just straight up give you discord link to Zero To Mastery, since it's not my group. In order to join Zero To Mastery discord group which currently has 37 thousands members  you need to purchase one of the Andrei Neagoie courses on Udemy:
https://www.udemy.com/user/andrei-neagoie/

I suggest to wait until prices drops below 15$ dollars and when purchase. My favorite course is junior-to-senior

**Comment by saadazghour** [comment]
Thanks for your suggestion  :+1:
